name: Code Formatter Check Using Black

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  black:
    name: Run Black
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Black
        run: |
          python -m pip install --upgrade pip
          pip install black

      - name: Run Black in check mode
        run: |
          black --check .
